nelmio_api_doc:
  documentation:
    components:
      schemas:
        GroupOfValuesId:
          properties:
            groupOfValuesId:
              description: ID of the created collection
              type: string
              format: uuid
          type: object

