nelmio_api_doc:
  documentation:
    components:
      schemas:
        UserSettingsEntry:
          properties:
            key:
              type: string
            value:
              type: string
            createdAt:
              type: string
              format: date-time
          type: object

